### ISSUE TITLE
Implement `purOrEffErrors` for Ratio

### ISSUE THREAD

**Issue by etyley** [cafana/CAFAnaCore#13]
As noted in the source code, the `purOrEffErrors` flag is currently ignored when creating a `Ratio`: https://github.com/cafana/CAFAnaCore/blob/7f232ee4a526b0ee8ab24b3c966c8a334045ccd0/CAFAna/Core/Ratio.cxx#L28

ROOT provides a `TEfficciency` class which has a series of functions to perform the calculation, the default is `ClopperPearson` but various frequentist and Bayesian options are provided: https://root.cern.ch/doc/v606/classTEfficiency.html#ae80c3189bac22b7ad15f57a1476ef75b

**Comment by cjbackhouse** [comment]
Any obvious issues with this? https://github.com/cafana/CAFAnaCore/commit/da7a2db1daefaa6321335a29f365800176ed1a52
Will need to merge into the relevant branch and make a new release to pick it up in SBN for proper testing.

**Comment by cjbackhouse** [comment]
Confirmed offline to work well.
